package odbclient

var serviceCommands = []struct {
	desc    string
	command OBDCommand
}{
	{"PIDs supported [01 - 20]", OBDCommand{0x01, 0x00}},
	{"Monitor status since DTCs cleared", OBDCommand{0x01, 0x01}},
	{"Freeze DTC", OBDCommand{0x01, 0x02}},
	{"Fuel system status", OBDCommand{0x01, 0x03}},
	{"Calculated engine load", OBDCommand{0x01, 0x04}},
	{"Engine coolant temperature", OBDCommand{0x01, 0x05}},
	{"Short term fuel trim—Bank 1", OBDCommand{0x01, 0x06}},
	{"Long term fuel trim—Bank 1", OBDCommand{0x01, 0x07}},
	{"Short term fuel trim—Bank 2", OBDCommand{0x01, 0x08}},
	{"Long term fuel trim—Bank 2", OBDCommand{0x01, 0x09}},
	{"Fuel pressure", OBDCommand{0x01, 0x0A}},
	{"Intake manifold absolute pressure", OBDCommand{0x01, 0x0B}},
	{"Engine RPM", OBDCommand{0x01, 0x0C}},
	{"Vehicle speed", OBDCommand{0x01, 0x0D}},
	{"Timing advance", OBDCommand{0x01, 0x0E}},
	{"Intake air temperature", OBDCommand{0x01, 0x0F}},
	{"MAF air flow rate", OBDCommand{0x01, 0x10}},
	{"Throttle position", OBDCommand{0x01, 0x11}},
	{"Commanded secondary air status", OBDCommand{0x01, 0x12}},
	{"Oxygen sensors present (in 2 banks)", OBDCommand{0x01, 0x13}},
	{"O2 Sensor 1 – Bank 1", OBDCommand{0x01, 0x14}},
	{"O2 Sensor 2 – Bank 1", OBDCommand{0x01, 0x15}},
	{"O2 Sensor 3 – Bank 1", OBDCommand{0x01, 0x16}},
	{"O2 Sensor 4 – Bank 1", OBDCommand{0x01, 0x17}},
	{"O2 Sensor 1 – Bank 2", OBDCommand{0x01, 0x18}},
	{"O2 Sensor 2 – Bank 2", OBDCommand{0x01, 0x19}},
	{"O2 Sensor 3 – Bank 2", OBDCommand{0x01, 0x1A}},
	{"O2 Sensor 4 – Bank 2", OBDCommand{0x01, 0x1B}},
	{"OBD standards this vehicle conforms to", OBDCommand{0x01, 0x1C}},
	{"Oxygen sensors present (in 4 banks)", OBDCommand{0x01, 0x1D}},
	{"Auxiliary input status", OBDCommand{0x01, 0x1E}},
	{"Run time since engine start", OBDCommand{0x01, 0x1F}},
	{"PIDs supported [21 - 40]", OBDCommand{0x01, 0x20}},
	{"Distance traveled with malfunction indicator lamp (MIL) on", OBDCommand{0x01, 0x21}},
	{"Fuel Rail Pressure (relative to manifold vacuum)", OBDCommand{0x01, 0x22}},
	{"Fuel Rail Gauge Pressure (diesel, or gasoline direct injection)", OBDCommand{0x01, 0x23}},
	{"O2 Sensor 1 – Bank 1 (wide range)", OBDCommand{0x01, 0x24}},
	{"O2 Sensor 2 – Bank 1 (wide range)", OBDCommand{0x01, 0x25}},
	{"O2 Sensor 1 – Bank 2 (wide range)", OBDCommand{0x01, 0x26}},
	{"O2 Sensor 2 – Bank 2 (wide range)", OBDCommand{0x01, 0x27}},
	{"Commanded EGR", OBDCommand{0x01, 0x2C}},
	{"EGR Error", OBDCommand{0x01, 0x2D}},
	{"Commanded evaporative purge", OBDCommand{0x01, 0x2E}},
	{"Fuel Level Input", OBDCommand{0x01, 0x2F}},
	{"# of warm-ups since codes cleared", OBDCommand{0x01, 0x30}},
	{"Distance traveled since codes cleared", OBDCommand{0x01, 0x31}},
	{"Evap. System Vapor Pressure", OBDCommand{0x01, 0x32}},
	{"Barometric pressure", OBDCommand{0x01, 0x33}},
	{"O2 Sensor 1 – Bank 1 (current)", OBDCommand{0x01, 0x34}},
	{"Oxygen Sensor 2 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x35, 4}},
	{"Oxygen Sensor 3 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x36, 4}},
	{"Oxygen Sensor 4 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x37, 4}},
	{"Oxygen Sensor 5 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x38, 4}},
	{"Oxygen Sensor 6 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x39, 4}},
	{"Oxygen Sensor 7 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x3A, 4}},
	{"Oxygen Sensor 8 (Air-Fuel Equivalence Ratio λ, Current)", OBDCommand{0x3B, 4}},
	{"Catalyst Temperature: Bank 1, Sensor 1", OBDCommand{0x3C, 2}},
	{"Catalyst Temperature: Bank 2, Sensor 1", OBDCommand{0x3D, 2}},
	{"Catalyst Temperature: Bank 1, Sensor 2", OBDCommand{0x3E, 2}},
	{"Catalyst Temperature: Bank 2, Sensor 2", OBDCommand{0x3F, 2}},
	{"PIDs supported [$41 - $60]", OBDCommand{0x40, 4}},
	{"Monitor status this drive cycle", OBDCommand{0x41, 4}},
	{"Control module voltage", OBDCommand{0x42, 2}},
	{"Absolute load value", OBDCommand{0x43, 2}},
	{"Commanded Air-Fuel Equivalence Ratio (lambda)", OBDCommand{0x44, 2}},
	{"Relative throttle position", OBDCommand{0x45, 1}},
	{"Ambient air temperature", OBDCommand{0x46, 1}},
	{"Absolute throttle position B", OBDCommand{0x47, 1}},
	{"Absolute throttle position C", OBDCommand{0x48, 1}},
	{"Accelerator pedal position D", OBDCommand{0x49, 1}},
	{"Accelerator pedal position E", OBDCommand{0x4A, 1}},
	{"Accelerator pedal position F", OBDCommand{0x4B, 1}},
	{"Commanded throttle actuator", OBDCommand{0x4C, 1}},
	{"Time run with MIL on", OBDCommand{0x4D, 2}},
	{"Time since trouble codes cleared", OBDCommand{0x4E, 2}},
	{"Maximum value for Fuel–Air equivalence ratio, oxygen sensor voltage, oxygen sensor current, intake manifold absolute pressure", OBDCommand{0x4F, 4}},
	{"Maximum value for air flow rate from mass air flow sensor", OBDCommand{0x50, 4}},
	{"Fuel Type", OBDCommand{0x51, 1}},
	{"Ethanol fuel %", OBDCommand{0x52, 1}},
	{"Absolute Evap system Vapor Pressure", OBDCommand{0x53, 2}},
	{"Evap system vapor pressure", OBDCommand{0x54, 2}},
	{"Short term secondary oxygen sensor trim, bank 1 and 3", OBDCommand{0x55, 2}},
	{"Long term secondary oxygen sensor trim, bank 1 and 3", OBDCommand{0x56, 2}},
	{"Short term secondary oxygen sensor trim, bank 2 and 4", OBDCommand{0x57, 2}},
	{"Long term secondary oxygen sensor trim, bank 2 and 4", OBDCommand{0x58, 2}},
	{"Fuel rail absolute pressure", OBDCommand{0x59, 2}},
	{"Relative accelerator pedal position", OBDCommand{0x5A, 1}},
	{"Hybrid battery pack remaining life", OBDCommand{0x5B, 1}},
	{"Engine oil temperature", OBDCommand{0x5C, 1}},
	{"Fuel injection timing", OBDCommand{0x5D, 2}},
	{"Engine fuel rate", OBDCommand{0x5E, 2}},
	{"Emission requirements to which vehicle is designed", OBDCommand{0x5F, 1}},
	{"PIDs supported [$61 - $80]", OBDCommand{0x60, 4}},
	{"Driver's demand engine - percent torque", OBDCommand{0x61, 1}},
	{"Actual engine - percent torque", OBDCommand{0x62, 1}},
	{"Engine reference torque", OBDCommand{0x63, 2}},
	{"Engine percent torque data", OBDCommand{0x64, 5}},
	{"Auxiliary input / output supported", OBDCommand{0x65, 2}},
	{"Mass air flow sensor", OBDCommand{0x66, 5}},
	{"Engine coolant temperature", OBDCommand{0x67, 3}},
	{"Intake air temperature sensor", OBDCommand{0x68, 3}},
	{"Actual EGR, Commanded EGR, and EGR Error", OBDCommand{0x69, 7}},
	{"Commanded Diesel intake air flow control and relative intake air flow position", OBDCommand{0x6A, 5}},
	{"Exhaust gas recirculation temperature", OBDCommand{0x6B, 5}},
	{"Commanded throttle actuator control and relative throttle position", OBDCommand{0x6C, 5}},
	{"Fuel pressure control system", OBDCommand{0x6D, 11}},
	{"Injection pressure control system", OBDCommand{0x6E, 9}},
	{"Turbocharger compressor inlet pressure", OBDCommand{0x6F, 3}},
	{"Boost pressure control", OBDCommand{0x70, 10}},
	{"Variable Geometry turbo (VGT) control", OBDCommand{0x71, 6}},
	{"Wastegate control", OBDCommand{0x72, 5}},
	{"Exhaust pressure", OBDCommand{0x73, 5}},
	{"Turbocharger RPM", OBDCommand{0x74, 5}},
	{"Turbocharger temperature", OBDCommand{0x75, 7}},
	{"Turbocharger temperature", OBDCommand{0x76, 7}},
	{"Charge air cooler temperature (CACT)", OBDCommand{0x77, 5}},
	{"Exhaust Gas temperature (EGT) Bank 1", OBDCommand{0x78, 9}},
	{"Exhaust Gas temperature (EGT) Bank 2", OBDCommand{0x79, 9}},
	{"Diesel particulate filter (DPF) differential pressure", OBDCommand{0x7A, 7}},
	{"Diesel particulate filter (DPF)", OBDCommand{0x7B, 7}},
	{"Diesel Particulate filter (DPF) temperature", OBDCommand{0x7C, 9}},
	{"NOx NTE (Not-To-Exceed) control area status", OBDCommand{0x7D, 1}},
	{"PM NTE (Not-To-Exceed) control area status", OBDCommand{0x7E, 1}},
	{"Engine run time [b]", OBDCommand{0x7F, 13}},
	{"PIDs supported [$81 - $A0]", OBDCommand{0x80, 4}},
	{"Engine run time for Auxiliary Emissions Control Device (AECD)", OBDCommand{0x81, 41}},
	{"Engine run time for Auxiliary Emissions Control Device (AECD)", OBDCommand{0x82, 41}},
	{"NOx sensor", OBDCommand{0x83, 9}},
	{"Manifold surface temperature", OBDCommand{0x84, 1}},
	{"NOx reagent system", OBDCommand{0x85, 10}},
	{"Particulate matter (PM) sensor", OBDCommand{0x86, 5}},
	{"Intake manifold absolute pressure", OBDCommand{0x87, 5}},
	{"SCR Induce System", OBDCommand{0x88, 13}},
	{"Run Time for AECD #11-#15", OBDCommand{0x89, 41}},
	{"Run Time for AECD #16-#20", OBDCommand{0x8A, 41}},
	{"Diesel Aftertreatment", OBDCommand{0x8B, 7}},
	{"O2 Sensor (Wide Range)", OBDCommand{0x8C, 17}},
	{"Throttle Position G", OBDCommand{0x8D, 1}},
	{"Engine Friction - Percent Torque", OBDCommand{0x8E, 1}},
	{"PM Sensor Bank 1 & 2", OBDCommand{0x8F, 7}},
	{"WWH-OBD Vehicle OBD System Information", OBDCommand{0x90, 3}},
	{"WWH-OBD Vehicle OBD System Information", OBDCommand{0x91, 5}},
	{"Fuel System Control", OBDCommand{0x92, 2}},
	{"WWH-OBD Vehicle OBD Counters support", OBDCommand{0x93, 3}},
	{"NOx Warning And Inducement System", OBDCommand{0x94, 12}},
	{"Exhaust Gas Temperature Sensor", OBDCommand{0x98, 9}},
	{"Exhaust Gas Temperature Sensor", OBDCommand{0x99, 9}},
	{"Hybrid/EV Vehicle System Data, Battery, Voltage", OBDCommand{0x9A, 6}},
	{"Diesel Exhaust Fluid Sensor Data", OBDCommand{0x9B, 4}},
	{"O2 Sensor Data", OBDCommand{0x9C, 17}},
	{"Engine Fuel Rate", OBDCommand{0x9D, 4}},
	{"Engine Exhaust Flow Rate", OBDCommand{0x9E, 2}},
	{"Fuel System Percentage Use", OBDCommand{0x9F, 9}},
	{"PIDs supported [$A1 - $C0]", OBDCommand{0xA0, 4}},
	{"NOx Sensor Corrected Data", OBDCommand{0xA1, 9}},
	{"Cylinder Fuel Rate", OBDCommand{0xA2, 2}},
	{"Evap System Vapor Pressure", OBDCommand{0xA3, 9}},
	{"Transmission Actual Gear", OBDCommand{0xA4, 4}},
	{"Commanded Diesel Exhaust Fluid Dosing", OBDCommand{0xA5, 4}},
	{"Odometer", OBDCommand{0xA6, 4}},
	{"NOx Sensor Concentration Sensors 3 and 4", OBDCommand{0xA7, 4}},
	{"NOx Sensor Corrected Concentration Sensors 3 and 4", OBDCommand{0xA8, 4}},
	{"ABS Disable Switch State", OBDCommand{0xA9, 4}},
	{"PIDs supported [$C1 - $E0]", OBDCommand{0xC0, 4}},
	{"Fuel Level Input A/B", OBDCommand{0xC3, 2}},
	{"Exhaust Particulate Control System Diagnostic Time/Count", OBDCommand{0xC4, 8}},
	{"Fuel Pressure A and B", OBDCommand{0xC5, 4}},
	{"Particulate control and counters", OBDCommand{0xC6, 7}},
	{"Distance Since Reflash or Module Replacement", OBDCommand{0xC7, 2}},
	{"NOx Control Diagnostic (NCD) and Particulate Control Diagnostic (PCD) Warning Lamp status", OBDCommand{0xC8, 1}},
}

func (c *ODBClient) GetTelemetry() map[string]string {
	res := make(map[string]string)
	for _, command := range serviceCommands {
		var (
			result string
			err    error
		)
		if result, err = c.Send(command.command); err != nil {
			continue
		}
		res[command.desc] = result
	}
	return res
}
